package panelMensaje;

import clases.Articulo;
import clases.Usuario;
import java.awt.Color;
import java.awt.Component;
import java.util.Iterator;
import java.util.List;
import javax.swing.Icon;
import javax.swing.JLabel;
import modelo.DAO;
import net.miginfocom.layout.ComponentWrapper;
import net.miginfocom.layout.LayoutCallback;
import vista.ParaTi;
import vista.Tienda;
import vista.Comprar;

/**
 *
 *
 * @author Bayron
 */
public class ItemTienda extends javax.swing.JPanel {

    private ParaTi paraTi;
    private Articulo ar;
    private DAO dao;
    private Usuario usu;
    private boolean tienda;
    private Tienda tien;
    private Comprar compra;

    /**
     * Genera una ventana que carga en el carrito de compra los articulos
     * guardados.
     *
     * @param icon
     * @param ar
     * @param dao
     * @param usu
     * @param tienda
     * @param tien
     * @param compra
     */
    public ItemTienda(Icon icon, Articulo ar, DAO dao, Usuario usu, boolean tienda, Tienda tien, Comprar compra) {
        initComponents();
        this.ar = ar;
        this.compra = compra;
        pic.setIcon(icon);
        lbName.setText(ar.getVendedor());
        lbDes.setText(ar.getDescripcion());
        lbTime.setText(Float.toString(ar.getPrecio()));
        this.tienda = tienda;
        this.tien = tien;
        this.dao = dao;

        this.usu = usu;

        if (!tienda) {
            borrar.setVisible(false);
        } else {
            this.setBackground(new Color(49, 51, 53));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbName = new javax.swing.JLabel();
        lbDes = new javax.swing.JLabel();
        lbTime = new javax.swing.JLabel();
        pic = new panelMensaje.ImageAvatar();
        borrar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(49, 51, 53));
        setOpaque(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        lbName.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        lbName.setForeground(new java.awt.Color(106, 106, 106));
        lbName.setText("Name");

        lbDes.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        lbDes.setForeground(new java.awt.Color(134, 134, 134));
        lbDes.setText("Description");

        lbTime.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        lbTime.setForeground(new java.awt.Color(134, 134, 134));
        lbTime.setText("a day ago");

        pic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                picMouseClicked(evt);
            }
        });

        borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pantalla/borrar (1)-removebg-preview (1).jpg"))); // NOI18N
        borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbName)
                        .addGap(20, 20, 20))
                    .addComponent(lbDes, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbTime)
                        .addContainerGap())
                    .addComponent(borrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbName)
                    .addComponent(lbTime))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDes)
                    .addComponent(borrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

    }//GEN-LAST:event_formMouseClicked

    private void picMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_picMouseClicked

    }//GEN-LAST:event_picMouseClicked

    private void borrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarMouseClicked
        List<Articulo> art = tien.getAr();
        Iterator<Articulo> arti = art.iterator();

        while (arti.hasNext()) {
            Articulo str = arti.next();

            if (ar.getId_articulo().equals(str.getId_articulo())) {
                arti.remove();
            }
        }

        boolean tienB = true;
        GlassPanePopup.closePopupAll();
        // GlassPanePopup.closePopup();
        GlassPanePopup.showPopup(new Notifications(usu, dao, tienB, art, tien, true, null), new DefaultOption() {

            @Override
            public float opacity() {
                return 0;
            }

            @Override
            public LayoutCallback getLayoutCallBack(Component parent) {
                return new DefaultLayoutCallBack(parent) {
                    @Override
                    public void correctBounds(ComponentWrapper cw) {
                        if (parent.isVisible()) {
                            cw.setBounds(215, 70, 380, 500);
                        } else {
                            super.correctBounds(cw);
                        }
                    }

                };
            }

        });

        if (art.size() == 0) {
            GlassPanePopup.closePopupAll();
            JLabel carrito1 = tien.getCarritoCompraLleno();
            carrito1.setVisible(false);
        }
        tien.cargarElementos(false);

        if (compra != null) {
            compra.dispose();
            Comprar comprar = new Comprar(tien, true, dao, art, usu);
            comprar.setVisible(true);
        }

    }//GEN-LAST:event_borrarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel borrar;
    private javax.swing.JLabel lbDes;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbTime;
    private panelMensaje.ImageAvatar pic;
    // End of variables declaration//GEN-END:variables
}
