/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tienda;

import clases.Articulo;
import excepciones.ErrAlter;
import excepciones.ErrVariados;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.JLabel;
import javax.swing.Timer;
import modelo.DAO;
import panelMensaje.Message;
import vista.AniadirProducto;
import vista.Tienda;

public class panelContenido2 extends javax.swing.JPanel {

    private Timer timer;

    private JLabel carritoCompra;
    private DAO dao;
    private Tienda tien;
    private boolean borrarB;
    private String id;
    private boolean modificar;
    private String descrip;
    private String prec;
    private String peso;
    private AniadirProducto produc;

    public panelContenido2(Icon icon, Icon image, String nombreP, String prec, String descrip, DAO dao, Tienda tien, boolean borrarB, String id, boolean modificar, String peso, AniadirProducto produc) {
        initComponents();
        setBackground(new Color(49, 51, 53));
        pic.setIcon(icon);
        this.dao = dao;
        this.produc = produc;
        this.descrip = descrip;
        this.prec = prec;
        this.peso = peso;
        this.borrarB = borrarB;
        this.modificar = modificar;
        this.id = id;
        imgArticulo1.setImage((Icon) image);
        this.tien = tien;
        vendedor.setText(nombreP);
        descripcion.setText(descrip);

        precioModificar.setText(prec);
        pesoModificar.setText(peso);

        vendedor.setForeground(Color.white);
        descripcion.setForeground(Color.white);
        pesoModificar.setForeground(Color.white);
        precioModificar.setForeground(Color.WHITE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelShadow = new tienda.PanelShadow();
        descripcion = new javax.swing.JTextField();
        imgArticulo1 = new tienda.PictureBox();
        pic1 = new panelMensaje.ImageAvatar();
        pic = new panelMensaje.ImageAvatar();
        vendedor = new javax.swing.JLabel();
        pesoModificar = new javax.swing.JTextField();
        precioModificar = new javax.swing.JTextField();
        lblModificar = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelShadow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        descripcion.setBackground(new java.awt.Color(41, 51, 53));
        descripcion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelShadow.add(descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 180, 60));

        imgArticulo1.add(pic1);
        pic1.setBounds(0, 0, 53, 44);

        panelShadow.add(imgArticulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 270, 140));
        panelShadow.add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 30));

        vendedor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        panelShadow.add(vendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 134, 30));

        pesoModificar.setBackground(new java.awt.Color(41, 51, 53));
        pesoModificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelShadow.add(pesoModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 100, 20));

        precioModificar.setBackground(new java.awt.Color(41, 51, 53));
        precioModificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelShadow.add(precioModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 100, 20));

        lblModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pantalla/boton-editar-removebg-preview (1).jpg"))); // NOI18N
        lblModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblModificarMouseClicked(evt);
            }
        });
        panelShadow.add(lblModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 50, 40));

        add(panelShadow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 340));
    }// </editor-fold>//GEN-END:initComponents

    private void lblModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModificarMouseClicked

        if (descripcion.getText().equalsIgnoreCase(descrip) && precioModificar.getText().equalsIgnoreCase(prec) && pesoModificar.getText().equalsIgnoreCase(peso)) {

            System.out.println("No haz hecho cambios!!");
        } else {
            try {
                Articulo art = new Articulo();
                art.setId_articulo(id);
                art.setDescripcion(descripcion.getText());
                art.setPrecio(Float.parseFloat(precioModificar.getText()));
                art.setPeso(Float.parseFloat(pesoModificar.getText()));
                dao.modificarArt(art);
                produc.dispose();
                tien.cargarElementos(false);
            } catch (ErrVariados ex) {
                ex.mostrarError();
            } catch (ErrAlter ex) {
                ex.mostrarError();
            }
        }

    }//GEN-LAST:event_lblModificarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField descripcion;
    private tienda.PictureBox imgArticulo1;
    private javax.swing.JLabel lblModificar;
    private tienda.PanelShadow panelShadow;
    private javax.swing.JTextField pesoModificar;
    private panelMensaje.ImageAvatar pic;
    private panelMensaje.ImageAvatar pic1;
    private javax.swing.JTextField precioModificar;
    private javax.swing.JLabel vendedor;
    // End of variables declaration//GEN-END:variables

}
