/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tienda;

import clases.Articulo;
import clases.Usuario;
import java.awt.Color;
import javax.swing.Icon;
import javax.swing.JLabel;
import javax.swing.Timer;
import modelo.DAO;
import vista.Tienda;

/**
 * Es una clase auxiliar que genera campos personalizados.
 *
 * @author Bayron
 */
public class panelCarrito extends javax.swing.JPanel {

    private Timer timer;

    private JLabel carritoCompra;
    private DAO dao;
    private Tienda tien;
    private boolean borrarB;
    private boolean modificar;
    private Usuario usu;
    private Articulo art;

    public panelCarrito(Icon image, DAO dao, Articulo art) {
        initComponents();
        setBackground(new Color(49, 51, 53));

        this.art = art;
        this.dao = dao;
        this.usu = usu;
        this.borrarB = borrarB;
        this.modificar = modificar;
        imgArticulo1.setImage((Icon) image);
        this.tien = tien;
        vendedor.setText(art.getVendedor());
        descripcion.setText(art.getDescripcion());
        precio.setText(Float.toString(art.getPrecio()));

        vendedor.setForeground(Color.white);
        descripcion.setForeground(Color.white);
        precio.setForeground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelShadow = new tienda.PanelShadow();
        precio = new javax.swing.JLabel();
        imgArticulo1 = new tienda.PictureBox();
        pic1 = new panelMensaje.ImageAvatar();
        vendedor = new javax.swing.JLabel();
        descripcion = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelShadow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        precio.setText(" ");
        panelShadow.add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 72, 16));

        imgArticulo1.add(pic1);
        pic1.setBounds(0, 0, 53, 44);

        panelShadow.add(imgArticulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 70));

        vendedor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        panelShadow.add(vendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 20, 80, 20));
        panelShadow.add(descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 140, 40));

        add(panelShadow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 110));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descripcion;
    private tienda.PictureBox imgArticulo1;
    private tienda.PanelShadow panelShadow;
    private panelMensaje.ImageAvatar pic1;
    private javax.swing.JLabel precio;
    private javax.swing.JLabel vendedor;
    // End of variables declaration//GEN-END:variables
}
